### ISSUE TITLE
Error exec command.

### ISSUE THREAD

**Issue by joarli** [jacobdjwilson/pfMailReport#1]
cat /var/log/auth.log | sh /usr/local/bin/pfMailReport.sh -l 'Authentication Log'
<h1 style="color:#fff;background-color:#000842;text-align:left;font-size:2em;width:100%;font-family:Arial;">Authentication Log</h1>
/usr/local/bin/pfMailReport.sh: 71: Syntax error: word unexpected (expecting ")")

**Comment by jacobdjwilson** [comment]
Thanks! Line 71 got dropped in the last commit and I added it back.
